### ISSUE TITLE
COMET doesn't work properly with Finnish regional settings (date format: dd.mm.yyyy)

### ISSUE THREAD

**Issue by ktiensuu** [RHEAGROUP/COMET-IME-Community-Edition#1009]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the COMET-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In the Finnish regional settings the date format is dd.mm.yyyy. Tried to add parameters to element definitions and to create element definitions, but couldn't do either. 

### Steps to Reproduce
Tried to add parameter to element definition and to create an element definition. 

### Logs
Error when trying to create element definition: The CDP4 Services replied with code InternalServerError: Internal Server Error: "exception:String was not recognized as a valid DateTime."

Error when trying to add parameters to element definitions: "Error. The parameter could not be created"

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [X] COMET-IME: ver. 9 and 10
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [X] Windows OS (32/64 bit): 64 bit
  - [ ] Additional information:

**Comment by omaratrhea** [comment]
@samatrhea Detecting the region or the datetime format ?

**Comment by samatrhea** [comment]
whatever combination is causing the problem

**Comment by omaratrhea** [comment]
That's possible
