### ISSUE TITLE
Parameter ModelCodes not reacting in ED Tree after update of the ED

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/COMET-IME-Community-Edition#1014]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When the shortname of an ED is edited, the model code of the underlying parameter rows in the ED tree is not automatically updated.

Check in ElementDefinition browser and Product Tree.

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by MartinFijneman** [comment]
verified with 9.2.0-RC6

verified in #1075
