### ISSUE TITLE
Parametric Constraints not working with Enumeration Parameter Types 

### ISSUE THREAD

**Issue by palomatrhea** [RHEAGROUP/COMET-IME-Community-Edition#1016]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
It is not possible to create parametric constraints for enumeration parameter types. An error appears in the "value" field independently of the selected operator.
![image](https://user-images.githubusercontent.com/86954172/152566883-bb513872-cd42-4658-bed8-836b0b2721c7.png)

### Steps to Reproduce
Create Requirement -> Add Parametric Constraint -> Create Relational Expression -> Select any Enumeration Parameter Type in the dropdown list.

### Logs

  - [x] There are no logs regarding the issue

  
### System Configuration

- COMET version:
  - [ ] COMET-IME: 9.0.1.1
  - [ ] Other: 
  
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 64 bit Windows 10
  - [ ] Additional information:

**Comment by MartinFijneman** [comment]
verified with 9.2.0-RC6
