### ISSUE TITLE
Excessive loading time and memory usage for Element Definitions View on large models

### ISSUE THREAD

**Issue by jamiewhths** [RHEAGROUP/COMET-IME-Community-Edition#1021]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the COMET-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Loading of models with a large number of element definitions and parameters (at present, circa 200 EDs containing ~5-20 Parameters per ED => on the order of 1000-2000 elements) causes full application lockup for more than 10 minutes, and in general results in unusable performance issues with the (latest) COMET IME client. 

The issue does not occur on initial loading of model and iteration. Upon opening the "Element Definitions" view, the loading freezes the application (appearing as a "Not Responding" state to the Task Manager), and the application memory usage balloons to an excessive level (in the range of 5-10 GB).

There are similar lockup issues when closing the Model/Iteration after loading the view. We observed a greater than 20 minute waiting period to close the iteration (with application freezing). Once the iteration is closed, the application keeps an excessive RAM usage (from 300 MB on fresh instance to 5.8GB afterwards) with no other models/iterations loaded. This smells like a memory leak on the client.

I noticed ticket #765 which discusses optimisations in the same direction as this problem, but at our scale the application performance is unusable at present.

This issue does not seem to be related to the performance of the web services, as the serialised data is returned efficiently (on the order of seconds for the whole iteration). The same issue occurs when loading from a JSON file.

#### Machine 1

**Element Definitions View - Opening time**
![sn-ed-load-time](https://user-images.githubusercontent.com/15144999/155144431-9ca461be-2099-411f-b616-015335c5ce6e.PNG)

**Memory Consumption**
![sn-memory-consumption](https://user-images.githubusercontent.com/15144999/155144467-77396126-21b2-4e0a-a697-6b7c94879b41.png)

#### Machine 2

**Element Definitions View - Opening time**
![jw-ed-load-time](https://user-images.githubusercontent.com/15144999/155144506-c2639b55-666c-431b-9e3c-4e6a3b23efda.PNG)

**Memory Consumption - With ED View / Iteration Open**
![jw-memory-consumption-opening](https://user-images.githubusercontent.com/15144999/155144597-a9a49986-8b2c-4676-9206-903167876695.PNG)

**Memory Consumption - With All Models/Iterations Closed**
![jw-memory-consumption-closed](https://user-images.githubusercontent.com/15144999/155144629-ded234ee-0bd8-4a19-a5f5-2cb4b45c85a7.PNG)

### Steps to Reproduce
- Load large model with many ElementDefinitions / Parameters (example model can be sent via email)
- Open Element Definitions View

### Logs

  - [X] There are no logs regarding the issue (no logs that I'm aware of but can provide if needed)
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [X] COMET-IME: 9.0.1.1
  - [ ] Other: 
  -
- Web Services:
  - [X] CDP4/COMET Web Services version: 4.0.0 (WSP) / 1.3.0 (DB)
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [X] Windows OS (32/64 bit): Win 10 64-bit
  - [ ] Additional information:

**Comment by samatrhea** [comment]
@jamiewhths we have identified the root cause of the loading times and high RAM usage. The root cause is the high amount of so-called "messagebus subscriptions" that we are using to make sure the content of the rows is updated when changes occur on the underlying model items. First trials to reduce this amount of subscriptions (so less naive and not a subscription per row in the view) has shown that loading times are reduced to approximately 45 seconds and RAM goes down dramatically as well. So, we will continue on this path to optimize the way the ElementDefinitions and ProductTree browser are built. It will take some time before we have a final solution but work is ongoing to resolve this issue. We keep you posted on progress.

**Comment by lxatrhea** [comment]
Opened the model.
Indeed a lot of data, and took over 9 minutes on my machine to open the ElementDefinitionBrowser.

Every ElementDefinition can be found 3 times in the model, so a lot of double information is in the model. I think it could be 3 times smaller:

 
![afbeelding](https://user-images.githubusercontent.com/56023674/155527855-fe7a9fea-6345-4bea-a6de-92b026277d20.png)


Every Parameter is Option Dependent, there are 5 Options in the model.

(at present, circa 200 EDs containing ~5-20 Parameters per ED => on the order of 1000-2000 elements)

1000 ElementUsages * 5 Parameters * 5 Options = 25.000 Parameter RowViewModels as a minimum.
1500 ElementUsages * 10 Parameters * 5 Options = 75.000 Parameter RowViewModels as expected.
2000 ElementUsages * 20 Parameters * 5 Options = 200.000 Parameter RowViewModels as a maximum.

Those are indeed some really big numbers!
And we know that MessageBus subscriptions can lead to excessive memory consumption.

**Comment by lxatrhea** [comment]
@alexatrhea wrote:

Perhaps we need to think of some more async and reactive ways to do this. From what I understand, the tree works fine when loaded? Either way we need to very much figure out a way to reduce memory footprint of what should be very very stupid simple row view models.

**Comment by lxatrhea** [comment]
@samatrhea wrote:

That sounds like a plan to me. Can we do a call to estimate effort together and plan to start working on this?

**Comment by lxatrhea** [comment]
Have been thinking about it.
No "bubbling", but use a (new) MessageBusHandler class that is instanciated at Browser level and is shared with each INewRowViewModelBase via their constructors. The class has (thread safe) information (Dictionaries) about all the INewRowViewModelBase instances. Data can be added/removed directly in the INewRowViewModelBase instances, because they all know the same MessageBusHandler. The MessageBusHandler can call specific methods at INewRowViewModel level that handle the "Events". Every Browser instance has it's own instance of MessageBusHandler.

**Comment by lxatrhea** [comment]
A quick test removing all MessageBus listeners for all RowViewModels reduces the loading time from 10 minutes to 40 seconds.
There might be more (unexpected) listeners  in the process, that could reduce the 40 seconds even more.
A alternative implementation however probably also adds loading time. The question is "How much?".

**Comment by jamiewhths** [comment]
@lxatrhea yes there is duplication in this model as we've been testing automated import scripts, but the final "production" version will be smaller in terms of # of EDs, but much larger in terms of EUs and Parameters per ED (I think the largest has reached nearly 100 parameters, nearly all option-dependent and a subset also state-depedendent).

**Comment by jamiewhths** [comment]
Some additional notes from today:
- I spotted that one of the parameter types we are using was actually a CompoundParameterType with a circular reference (Readout Noise.bol: Readout Noise...). I suspect this is could be contributing to the problem as it might be generating infinite loops - maybe there is a "short-circuit" needed in those cases and prevention of circular references when creating parameter types in the first instance.
- Fixing that parameter type caused the load time to massively reduce (down to 1m30s for me and 2m30s for my colleague, still not great but a big improvement). We are still sitting around 4-5GB with this new setup with ElementDefinition view loaded
- Opening the Product Tree views still has a bit of a lag (approx. 20s)

Maybe you can check on your side to confirm what we're seeing.

**Comment by lxatrhea** [comment]
@jamiewhths That is good news!!
Could you please sent us an updated annex C3 file, so we can check our "MessageBus-less" scenario?

**Comment by jamiewhths** [comment]
@lxatrhea sent via email. This is a re-import into a new model on a fresh deployment (upgraded to WSP 7.0.4/DB 2.0.0), with the "circular" parameter type problems resolved. It has 6 options configured, so a little higher than the earlier model (which will probably be our desired number for production).

Some additional statistics on the load this morning:

**Loading Element Definition view**

![image](https://user-images.githubusercontent.com/15144999/155687935-5a65aff5-f14b-4707-a748-798bfa2c23bd.png)

**Resource Usage in Task Manager**

![image](https://user-images.githubusercontent.com/15144999/155688101-8d66dbd3-198e-4a38-9962-169e717dc4df.png)

**Loading Option Tree view**

![image](https://user-images.githubusercontent.com/15144999/155688298-43514dc8-83a8-44ca-87e8-2235569fdf61.png)

**Comment by MartinFijneman** [comment]
verified with 9.2.0-RC1

performed multi-user test with a wide variety of actions, e.g.:
* add/edit/delete element definitions, element usages
* add/delete parameters, including edting parameter types
* add/edit/options (for product trees, with different top elements)
* add/delete subscriptions
* apply state and option dependency to parameters
* add/delete element usages (with exclusion in options)
* relationships (parameter to parametric constraint, between EDs, EUs and combinations)
* value sets: change values, switch, publish,... for all parameter types
