### ISSUE TITLE
Deprecated Domains still available when editing Active Domains in Model

### ISSUE THREAD

**Issue by patrick-lux** [RHEAGROUP/COMET-IME-Community-Edition#1022]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When editing the Active Domains of a Model the list shows all Domains available in the Directory. This includes Domains marked as "deprecated". These deprecated domains should not be available when editing a current model. 

Active Domains in Model Setup: 
![DeprecatedDomainsVisibleEditModel](https://user-images.githubusercontent.com/100347325/155503060-f028cd25-7305-4031-8169-73039d8de72c.PNG)

All Domains in Site Directory (Testaaa and Transport Process Engineering are deprecated): 
![DeprecatedDomains](https://user-images.githubusercontent.com/100347325/155503176-5ecdd515-3a26-49db-be66-4befbd36268c.PNG)

Only Implement "hiding" deprecated rows, which means filtering the list of possible domains.
No extra visual implementation (don't implement gray out).

### Steps to Reproduce

In the Directory Tab / Models / Edit Engineering Model Setup navigate to the Active Domains tab to see the list. 

### Logs

  - [x] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 9.0.1.1
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): Windows 10 Enterprise, 64bit, 21H1 19043.1466
  - [ ] Additional information:

**Comment by samatrhea** [comment]
The reason that now all domains are visible is that when a model exists with domains assigned and a domain becomes deprecated that this stil needs to be visible. We can however implement that ones a domain is deprecated that from the UI it cannot be assigned anymore but is still visible or can be made visible. In any case, 10-25 does not dictate that deprecated domains can no longer be assigned as active domains,. So it would be convenience in the UI.

@patrick-lux would that be a good way forward in your opinion?

**Comment by patrick-lux** [comment]
Yes If I understand correctly I would agree with the following: 
- make deprecated domains not visible by default in this window 
- I agree that there can be a filtering possibility to still make them visible and even assign them to models if this is ok by 10-25

**Comment by MartinFijneman** [comment]
verified with 9.2.0-RC1

implementation done for toggling icon to show or hide deprecated domains implemented.
possible to unassign a deprecated domain, not possible however to assign a deprecated domain to a model, which should still be possible, as explained by Sam. this posted as separate remaining issue, #1067
