### ISSUE TITLE
Closing the Publication Window causes COMET IME Crash

### ISSUE THREAD

**Issue by patrick-lux** [RHEAGROUP/COMET-IME-Community-Edition#1027]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [ ] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have observed this crash on multiple occasions. When I close the publication window while having also other windows open inside COMET IME (e.g. Element Definitions) I get the following error message leading to a complete crash & close of the COMET IME. 

![Closing-PublicationWindow2](https://user-images.githubusercontent.com/100347325/155513786-fec65b4b-7f62-4a74-8478-9173aa015d70.PNG)
![Closing-PublicationWindow](https://user-images.githubusercontent.com/100347325/155513793-a9cfddc4-315f-4e8c-9cbc-69c1f0a679c9.PNG)

Trying to save the above error report leads to another error message. 
[CannotSave Error Report.txt](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/files/8132012/CannotSave.Error.Report.txt)

### Steps to Reproduce

Happens sporadically when trying to close the publication window. 
Seems random to me when it occurs and when it does not. Cannot systematically reproduce it but observed it multiple times (>15) when using COMET IME extensively over 2 weeks. 

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 9.0.1.1
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): Win 10 64 bit Enterprise 21H1 19043.1466
  - [ ] Additional information:

**Comment by alexatrhea** [comment]
I just tried to reproduce it with no success. Can we schedule a small call on this in the near future @patrick-lux ?

**Comment by alexatrhea** [comment]
I think I found it.

**Comment by samatrhea** [comment]
good news, what's the issue?

**Comment by alexatrhea** [comment]
Not the same root cause, the publication browser could enter in some state where the browser was disposing but the row view model could trigger an update and query a property of the Thing, which at this point would be `null`. Switching domain likely something else.
