### ISSUE TITLE
Publication Tab could be more readable + past publications should be sorted chronologically 

### ISSUE THREAD

**Issue by patrick-lux** [RHEAGROUP/COMET-IME-Community-Edition#1030]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [ ] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

**Feature Request Low Prio Issue 1**: It is still very hard to see what has been changed and is waiting for publication. The only ways to find out are: 
	1) In the Publication Tab itself: 
		i. Find small arrows (hard to see at quick glance - suggest highlighting in blue & bold) 
		ii. Read/decipher model code to work out what has been updated (suggest adding Short Name + parameters below) 
	2) OR in the Element Definition Tab 
		i. Go one by one expanding each equipment to see if any lines turned blue (suggest turning the entire element definition blue again) 
			i. This is fine for 3 pieces of equipment but not for 30+
	
One takes a long time to match the values to the equipment and the other takes a long time to expand all the equipment. To simply publish things without checking is also not advisable especially at the moment as everyone is still learning COMET and there may be mistakes in the equipment that should be fixed first.

**Feature Request Low Prio Issue 2**: The list of past publications is sorted strangely by default 
In my opinion nothing else than by date (most recent at the top) makes sense 

![PublicationWindow-Issues](https://user-images.githubusercontent.com/100347325/155516985-9edb9ed2-18cb-4fda-bbd1-b64247ecdc0f.PNG)

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 9.0.1.1 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): Win 10 64 bit Enterprise 21H1 19043.1466
  - [ ] Additional information:

**Comment by samatrhea** [comment]
@patrick-lux can you suggest a way forward for feature request 1, you state an issue, would be great to get some hints on how to improve in your opinion

For feature request 2 we create a separate issue

**Comment by patrick-lux** [comment]
I would suggest something like in the Element definition Tab: subsystem highlighted blue and bold (rather than just by the arrow) 
Furthermore I suggest including the Short Name of the element definition in question more prominently (maybe as additional column all to the left next to the parameter name) rather than just having this as part of the model code

**Comment by alexatrhea** [comment]
I propose to you the following improvements:

1. Added toggle button (red circle) that allows to hide Domains with no publishable parameters.
2. Domains with publishable params or overrides as well as those rows are blue and bold
3. Element Shortname column added
4. Context menu added with following options: Inspect, Highlight and Highlight Element. The last two will actually expand and bring into focus the parameter that you want if the Element Definition tree is open.

![image](https://user-images.githubusercontent.com/22167021/156186062-ee818f8b-ad82-4dbe-a393-4cc5ff637c43.png)

Hope these changes are sufficient to improve the functionality.

**Comment by patrick-lux** [comment]
This looks good to me 
If J.Vennekens agrees I suggest it to be implement this way
