### ISSUE TITLE
Reporting enhancements

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/COMET-IME-Community-Edition#1035]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Please make the following Reporting plugin enhancements:

- DevExpress 20.2.10 upgrade (for Cross Tab to start working again)
- Implement outputting text to the Output panel from within the Code Editor for debugging purposes
- Bugfix writing Option Dependent parameters back to the model
- Add Extension methods to create DataTable objects from IEnumerable<T> objects
- Set "cursor" to the end of the Error/Output panels when text is added to them.

**Comment by MartinFijneman** [comment]
implementation testing depends on available suitable models/reports. is sufficiently tested by @lxatrhea with operational models/reports, not needed to test separately with 9.1.0 RC2 release testing
