### ISSUE TITLE
Model Directory shows Model iterations in strange order

### ISSUE THREAD

**Issue by patrick-lux** [RHEAGROUP/COMET-IME-Community-Edition#1044]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
 

When I look at the iterations of my model in the model tab the order of the list of iterations is strange. It is not order chronologically by the iterations (which is what I would have expected). It is also not ordered alphabetically by the descriptions.  

Same behavior seen for different models having more than 1 iteration. 

I would suggest displaying them in chronological order to avoid confusion. 

![IterationOrder1](https://user-images.githubusercontent.com/100347325/162679633-43fbfbd3-db61-4f1c-b06f-98c33859df58.PNG)

![IterationOrder2](https://user-images.githubusercontent.com/100347325/162679644-3b7be015-a8c0-4e9d-a982-6142ab321638.PNG)

![IterationOrder3](https://user-images.githubusercontent.com/100347325/162679649-09a6e811-ec0b-4886-a792-e5991864a05b.PNG)

### Steps to Reproduce
 

Navigate to Directory / Model open "Iterations" for a model that contains several iterations 

### Logs

  - [x] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 9.1.0.2
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): Win 10 64 bit Enterprise 21H1 19043.1466
  - [ ] Additional information:

**Comment by alexatrhea** [comment]
Really good first issue @omaratrhea

**Comment by MartinFijneman** [comment]
verified with 9.2.0-RC1
