### ISSUE TITLE
Reporting: Write back to model incorrect when using options 

### ISSUE THREAD

**Issue by patrick-lux** [RHEAGROUP/COMET-IME-Community-Edition#1062]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
 

In the current model I have defined 2 design options and made the total dry mass parameter option dependent. When I want to submit the total dry mass calculated from the mass budget using the "path" parameter it does not work intuitively or will necessitate the usage of different version of the mass budget report template.  

Scenario 1: When I include one of the possible Option "Extension" in the path in the reporting tab then the parameter gets always submitted to that option in the parameter. This happens even if the report gets compiled for the other option. 

Scenario 2: When I do not include the Option "Extension" in the path then the computed value gets submitted to both options in the parameter. 

From my point of view the suggested change would be to use Scenario 2 in the reporting tab and not specify the option but then automatically detect which option the report was compiled for and only submit to that option. This would avoid the need for creating different mass budget report templates using scenario 1 for each option. 

### Steps to Reproduce

Starting point: dry mass parameter is option dependent 
![DryMass_Parameter_OptionDependant](https://user-images.githubusercontent.com/100347325/168251864-3e9cd545-a867-422a-b5fa-1ec1c1c409f3.PNG)

**Scenario 1** 
Option is specified in path property in report design
![MassBudget_PathSetOPT](https://user-images.githubusercontent.com/100347325/168251992-cbb262e7-cb34-4158-95fa-32f8f058e67a.PNG)

When the report is compiled for the corresponding option the behavior is correct 
![MassBudget_SubmitParam_OPTset](https://user-images.githubusercontent.com/100347325/168252056-b7bf185d-fbff-4488-9dae-6496c5080917.PNG)

When the report is compiled for a different option the value still gets pushed to the option indicated in the path property. This will cause wrong values to appear in the model.
![MassBudget_SubmitParam_OPTset_INCORRECT](https://user-images.githubusercontent.com/100347325/168252134-82e2ad02-0645-4106-af07-3eeaebe8e2e2.PNG)

**Scenario 2**
Option is not specified in path property in report design
![MassBudget_PathSetNO-OPT](https://user-images.githubusercontent.com/100347325/168252314-f1df4e6c-af22-4a96-927e-5d6036abbe77.PNG)

Even though the report is only compiled for one option the same value would now be pushed to both options. This will also cause a wrong value to appear in the model. 
![MassBudget_SubmitParam_OPT_NotSet_INCORRECT](https://user-images.githubusercontent.com/100347325/168252442-00ae5447-ca24-4531-badc-3357a82c7e99.PNG)

### Logs

  - [x] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 9.1.0.2
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): Win 10 64 bit Enterprise 21H1 19043.1466

  - [ ] Additional information:

**Comment by patrick-lux** [comment]
Note: we noticed that this behavior was different in version 9.0.1.1 of the COMET IME that we have been using before. 
In this context Scenario 1 where you specify the path for one specific option would automatically detect the correct option and only push to that parameter. The first option from the list which is also the default option as been selected with the path. 

- Note the screenshots are from a different model using different option names but on the same CDF server
- Note that the screenshots submits to different parameters (dry mass & wet mass) back to the model correctly for the option as opposed to the screenshots above where the same value would be submitted into the options of a single parameter (dry mass) 

Default option is included in the path in the report design: 
![Inkedv9011_DefaultOptionSelected_LI](https://user-images.githubusercontent.com/100347325/168259850-2b982c5b-ef78-488a-89ab-ed3fb46e0820.jpg)


When the report is now compiled for an option different from the one given in the report design the parameter gets submitted correctly 
![Inkedv9011_DefaultOptionSelected_LI](https://user-images.githubusercontent.com/100347325/168259869-645ff721-5c18-4a67-b48c-6e18084d67d4.jpg)

**Comment by MartinFijneman** [comment]
verified with 9.2.0-RC3

using "path=..." allows to write back values for option for the selected option when running the report
using "exactpath=... " will write to that specific parameter in the specified option as given in the modelpath, independent of the selected option when running the report
