### ISSUE TITLE
HighlightByCategory 9.2.0 bugs

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/COMET-IME-Community-Edition#1069]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
- Hightlight ElementUsage does not work on ElementUsages in the ElementDefinition browser.
- Highlight by Category does not take super Categories into account
- Highlight by Category does not take into account, that an ElementUsage is also member of the Categories of its ElementDefinition.

**Comment by MartinFijneman** [comment]
verified with 9.2.0-RC3

- [X] Hightlight ElementUsage on ElementUsages in the ElementDefinition browser.

- [X]    Highlight by Category takes super Categories into account

- [X]  Highlight by Category takes into account, that an ElementUsage is also member of the Categories of its ElementDefinition.
