### ISSUE TITLE
ModelCode updates

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/COMET-IME-Community-Edition#1075]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Some that should reflect in ModelCode updates  do not yet work correctly in ElementDefinition browser and Product Tree

**Element Definition browser:**
- [x] Changing an ElementDefinition shortname is not reflected in Model codes for Parameter rows
- [x] Changing a ParameterType shortname is not reflected in Parameter row
- [x] Changing an Option shortname is not reflected in all Parameter related rows
- [x] Changing a PossibleFiniteState shortname is not reflected in all Parameter related rows

**Product Tree:**
- [x] Changing an ElementDefinition shortname is not reflected in Model codes for Parameter rows
- [x] Changing a ParameterType shortname is not reflected in any row
- [x] Changing an Option shortname is not reflected in all Parameter related rows
- [x] Changing a PossibleFiniteState shortname is not reflected in all Parameter related rows

**Comment by MartinFijneman** [comment]
verified with 9.2.0-RC6

all changes reflected with expected result

[V] Changing an ElementDefinition shortname is not reflected in Model codes for Parameter rows
[V] Changing a ParameterType shortname is not reflected in Parameter row
[V] Changing an Option shortname is not reflected in all Parameter related rows
[V] Changing a PossibleFiniteState shortname is not reflected in all Parameter related rows

Product Tree:

[V] Changing an ElementDefinition shortname is not reflected in Model codes for Parameter rows
[V] Changing a ParameterType shortname is not reflected in any row
[V] Changing an Option shortname is not reflected in all Parameter related rows
[V] Changing a PossibleFiniteState shortname is not reflected in all Parameter related rows

tested and verified as well:
Changing an ElementUsage shortname is not reflected in Model codes/paths for Parameter rows
* tested with parameter
* tested with parameter override
