### ISSUE TITLE
ParameterTypeComponent scale selection does not persist

### ISSUE THREAD

**Issue by jamiewhths** [RHEAGROUP/COMET-IME-Community-Edition#1133]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the COMET-IME (9.2.0-RC6)
- [X] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When creating a CompoundParameterType, the selection of a ParameterTypeComponent's `scale` does not persist and reverts to the default scale of the component's ParameterType.

Creating CompoundParameterType `comp_scale_test`:

![image](https://user-images.githubusercontent.com/15144999/176468525-51b720a5-522e-463a-93de-007518453c65.png)

Inspecting `comp_scale_test` after persist:

![image](https://user-images.githubusercontent.com/15144999/176468753-d452265d-0154-4a6f-bd5b-06b9034e76f2.png)

### Steps to Reproduce
1. Open Parameter Types View
2. Create a Compound Parameter Type
3. Add required metadata
4. Add a component parameter type with multiple measurement scales (e.g. length)
5. Change the component's scale to any scale other than the default scale
6. Save and persist parameter type
7. Inspect created parameter type, scale has reverted to default scale

### Logs

  - [X] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [X] COMET-IME: 9.2.0-RC6
  - [ ] Other: 
- Web Services:
  - [X] CDP4/COMET Web Services version: 7.0.4 (WSP) / 2.0.0 (DB)
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [X] Windows OS (32/64 bit): Win 10 Enterprise 64-bit 19043.1706
  - [ ] Additional information:

**Comment by lxatrhea** [comment]
@jamiewhths Looks like this is a COMET Server problem. I will investigate further.
