### ISSUE TITLE
As a user i would like to enable/disable tooltips in the application

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-IME-Community-Edition#1142]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When working with models and showing them to other people during screensharing sessions (demos) the tooltip text that pop when a mouse-over occurs become distracting. It would be great to have an application setting in which this can be enabled/disabled.

Solution:
- Create a button in the "View" Ribbon that toggles the "showtooltip" state.
- Implement reacting to "showtooltip" in the TooltipService

### Steps to Reproduce
NA

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- COMET version:
  - [ ] COMET-IME: 9.x
  - [ ]

**Comment by MartinFijneman** [comment]
verified with 9.3.0 RC1
* toggle of tooltips working
* slight delay in tooltips appearing when on
* text with modifier keys moved to details only
