### ISSUE TITLE
Requirements verification causes exception if no top element is set

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/COMET-IME-Community-Edition#1153]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Performing requirements verification causes an exception of the COMET-IME - 

The container Iteration of Option default does not have a TopElement specified

After this exception, the application crashes.

**Solution:**
the fix should be that in case no top element is set the app should display a popup stating this after the "verify" action is clicked/selected on the menu and then exit the operation so the user can fix this in the model

### Steps to Reproduce

* started from model with top element (e.g. LOFT on public server for testing to see if issue was reproducible)
* setup requirements specification, requirement with parametric constraint
* link parametric constraint to a parameter
* unset the top element so that no element exists as top element

### Logs

  - [X] There are no logs regarding the issue > easily reproducible, text from exception report given above
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [X] COMET-IME: 9.2.0.6
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
the fix should be that in case no top element is set the app should display a popup stating this after the "verify" action is clicked/selected on the menu and then exit the operation so the user can _fix_ this in the model

**Comment by MartinFijneman** [comment]
verified with 9.3.0 RC1

working, receiving notification that top element is not set.
