### ISSUE TITLE
Auto-refresh parameter values in Parameter to State Mapper

### ISSUE THREAD

**Issue by stepjah** [RHEAGROUP/COMET-IME-Community-Edition#1240]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The Parameter to State Mapper does not consider updated ParameterValues when loading an existing mapping but reads the value that is stored in the target mapping string. Only after  manually deselecting and selecting the mapped state again, the new parameter value is read from the model and updated in the mapping table. This is almost impossible to maintain for big models and continuous changes of the parameter values. The user need is to once define the mapping to a state and then always dynamically update the mapped value. 
An easy solution would be to implement a "refresh" button in the Parameter to State Mapper once going through all defined mappings and updating the mapped values in the mapping table. 
Alternatively the mapped value should not be stored in the target mapping string at all and the parameter to state mapper always directly reading from the model when loading a mapping.

### Logs

  - [x] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 9.4.0
  - [ ] Other: 
  -
- Web Services:
  - [x] CDP4/COMET Web Services version: 7.0.6.0
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [x] Microsoft Excel (32/64 bit): 64
  - [x] Windows OS (32/64 bit): 32
  - [ ] Additional information:

**Comment by stepjah** [comment]
Is there a chance to put some priority and this issue and implement this in feature in an upcoming version? This is a pain point that is reported frequently from the projects applying the tool. Thanks a lot!

**Comment by lxatrhea** [comment]
> Is there a chance to put some priority on this issue and implement this feature in an upcoming version? This is a pain point that is reported frequently from the projects applying the tool. Thanks a lot!

@stepjah:  You can find the new IME 9.7.0 release candidate here: https://github.com/RHEAGROUP/COMET-IME-Community-Edition/releases/tag/9.7.0-rc1
Please let me know if this works for you.

**Comment by stepjah** [comment]
@lxatrhea I can confirm that the update solves this issue and is a great improvement!
