### ISSUE TITLE
Domain File Store - "Created on" column shows date in different formats

### ISSUE THREAD

**Issue by omaratrhea** [RHEAGROUP/COMET-IME-Community-Edition#1249]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

In the Domain File Store "Created on" column shows the date in different formats.
In the below example, 2 formats are used dd/MM/yyyy and MM/dd/yyyy 
![image](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/assets/104059834/a79d6c75-6981-4291-9a71-1e8084de93d5)

### Steps to Reproduce

These are the steps i did:
1. Create a new Domain File Store
2. Add a file to the newly created File Store

### Logs

  - [x] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 9.4.0.2
  - [ ] Other: 
  
- Web Services:
  - [x] CDP4/COMET Web Services version: 7.0.6.0
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): Windows 11 64 bit
  - [ ] Additional information:

**Comment by MartinFijneman** [comment]
verified with 9.6.0.0

creation timestamp aligned in formatting

![image](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/assets/35371313/c6b38211-5d1d-42d9-9073-7ff22d952418)
