### ISSUE TITLE
draft version 9.4.2 quick test - python script gives syntax error

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/COMET-IME-Community-Edition#1254]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

testing python script for summation of masses in engineering model not working in draft version of 9.4.2, gives following error message when trying to run:

An error occured during the execution of the script !
Error: invalid syntax

Note: performed reference test using same testing file in version 9.4.1, there it is working

Note: testing performed with draft installation file provided by Alexander
related to #1253 

### Steps to Reproduce

* opened engineering model LOFT on public server
* opened testing python script: SpaceDemo_massBudget - LOFT.py
(attached copy of this testing script file, renamed to .txt)
[SpaceDemo_massBudget - LOFT.py.txt](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/files/11664921/SpaceDemo_massBudget.-.LOFT.py.txt)

* select session
* run script
this gives the error message

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
the update is for Python 3.4, the file you have is old python 2.7. Please use the folllowing script https://github.com/RHEAGROUP/COMET-IME-Community-Edition/blob/development/CDP4Scripting.Tests/sample/CDP4%20python-script-2.py

**Comment by MartinFijneman** [comment]
with other provided python script it is working as expected for this version (9.4.2). issue closed
