### ISSUE TITLE
[Grapher] when there is no topelement the grapher does not show

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-IME-Community-Edition#1260]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When there is no topelement and the grapher is selected, the panel does not show and it is not immediately clear why. After some thinking i realized the model did not have a top element. This needs to be more apparant, My proposal would be to:
  [ ] show the grapher with one box in the center which states very explicitly "no top node available" (OR)
  [ ] do not show the grapher and show a messagebox that says "no top node available"

### Steps to Reproduce

1. create a model with at least one Element Definition 
2. none of the Element Definitions should be marked as top element
3. try to open the grapher and see that nothing happens
4. make one Element Definition the top node
5. try to open the grapher and see that it displays

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 9.6.0.0

**Comment by samatrhea** [comment]
maybe related to #1216

**Comment by jaimeatrhea** [comment]
fixed in #1261

**Comment by MartinFijneman** [comment]
verified with 9.6.0.0

message displayed in grapher browser

![image](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/assets/35371313/b40ba8d0-7ba7-4b3a-9bd2-ca7d5cc7580d)
