### ISSUE TITLE
After filtering and sorting in the ED browser, the COMET-IME may crash

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-IME-Community-Edition#1264]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [ x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Closing the element definitions browser still causes COMET to freeze and/or crash (this seems to be more likely to happen if I have applied some filtering & sorting in the browser or expanded some drop-down lists)

### Steps to Reproduce
open a model, naviage to the ED browser and apply filtering and sorting and expand various drop-down lists

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 9.5.0

**Comment by alexatrhea** [comment]
Particularly sorting. Reproduction shown by ESA. Sorting on any column, and then trying to close the ED browser makes it hang. Reproduced by @lxatrhea on local machine.

**Comment by alexatrhea** [comment]
Update: seems that the problem is persistent to other browsers as well.

**Comment by lxatrhea** [comment]
This happens when RevisionNumber is reset to 0 for all ViewModels in the IME. This typically happens on Dispose of the Browser.
Somehow, the NotifyChanged event is handled by DevExpress and some code is executed when a filter or sort is active on a TreeListControl, which leads into a repaint/refresh of the UI.

**Comment by MartinFijneman** [comment]
verified with 9.6.0.0

various tests performed which would lead to crash, now not happening anymore, ED browser correctly disposed

**Comment by samatrhea** [comment]
this fix is for all views that provide the mentioned filtering and sorting capability and is not limited to the ED only
