### ISSUE TITLE
[Create Participant] not working in version 10 RC

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-IME-Community-Edition#1300]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Creating a participant no longer works in version 10-rc4

### System Configuration

- COMET version:
  - [ ] COMET-IME: [10.0.0-rc4](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/releases/tag/10.0.0-rc4)

- Web Services:
  - [x] CDP4/COMET Web Services version: 8-rc15

**Comment by palomatrhea** [comment]
Still applicable to version 10.0.0-rc5

**Comment by lxatrhea** [comment]
@palomatrhea Fixed in 10.0.0-rc6
