### ISSUE TITLE
IValidationService from SDK

### ISSUE THREAD

**Issue by antoineatrhea** [RHEAGROUP/COMET-IME-Community-Edition#1306]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

A IValidationService has been implement on the SDK (CDP4Common).
This ValidationService is a similar implementation of the one present inside the IME but at a common place. 

That new ValidationService should be use.

Remarks : 
Part of the ValidateProperty implementation is slightly different since we do not have access to VM
### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by lxatrhea** [comment]
@antoineatrhea Can this issue be closed?
