### ISSUE TITLE
As a User I want to Display more than one Relationship Matrix at the same time

### ISSUE THREAD

**Issue by credondorhea** [RHEAGROUP/COMET-IME-Community-Edition#163]
### Prerequisites

- [ X] I have written a descriptive issue title
- [X ] I have verified that I am running the latest version of the CDP4-IME
- [X ] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Logs

  - [x] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X ] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ X] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by alexatrhea** [comment]
Please provide the use case for this?

**Comment by alexatrhea** [comment]
@samatrhea this would be counterpattern as the whole thing is an `Iteration` thing panel, with the usual Ribbon toggle.

**Comment by samatrhea** [comment]
@alexatrhea yes indeed, we'll have to understand the request a bit better before we can think about implementing this,

**Comment by credondorhea** [comment]
I will try to explain the rationale behind this idea. 
I am currently building a Requirement Tree with the following hierarchy:
-Science Requirements (science descriptor), in different levels.
-Mission Requirements (mission descriptor) in one level.
-Specific Domain of Expertise Requirements. (AOCS descriptor, thermal descriptor...) in one level.

Therefore, I have the following relationships, all of them "Parent ID" relationships:
-Science Requirements with other Science Requirements that are in a higher level.
-Mission Requirements to Science Requirements.
-DoE Requirements to Mission/Science Requirements.

With the current configuration of the Relationship Matrix, I can not have a simultaneous look at the tree  in a way that clearly divide the 3 relationships (also, the relationships have the same name: "Parent ID", so I can not use the relationship to filter). This is how it would look like seeing everything at the same time:

![Github idea1](https://user-images.githubusercontent.com/50144749/60518674-3f4c0780-9ce2-11e9-918c-8e8ad58739d5.PNG)

This is what would I like to see, in separate Matrix:
-Relationships between Science Requirements.
![Github idea2](https://user-images.githubusercontent.com/50144749/60518690-4c68f680-9ce2-11e9-8a77-c449ea9e16cc.PNG)

-Relationships between Mission to Science Requirements
![Github idea3](https://user-images.githubusercontent.com/50144749/60518693-4d9a2380-9ce2-11e9-8619-452216354324.PNG)

-Relationships between DoE to Mission/Science Requirements

![Github idea 4](https://user-images.githubusercontent.com/50144749/60519357-addd9500-9ce3-11e9-968b-2a0d9f3b4699.PNG)



In general, it would be good for traceability when it is needed to display relationships simultaneously not to lose the track (be able to jump from a relationship to another without having to configure a new matrix).

**Comment by samatrhea** [comment]
implemented when we implemented showing multiple browsers of the same type at the same time
