### ISSUE TITLE
Display Generic COMET information by clicking COMET logo (top left part of screen)

### ISSUE THREAD

**Issue by credondorhea** [RHEAGROUP/COMET-IME-Community-Edition#167]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
For a user it is intuitive to use the COMET logo at the top left part of the screen to request generic COMET information (such as current version). This can also be done by clicking "About" in the "Home" ribbon.

Do the same for the Informationbutton in the upper right corner.
Also add a proper tooltip text to that information button.

### Logs

  - [x] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by MartinFijneman** [comment]
verified with 9.4.0 RC2

implementation done for COMET logo

request in this issue for same implementation to be done on information icon in top right corner created as separate new issue
#1235
