### ISSUE TITLE
Disable Active Domains tab completely on EngineeringModelSetup creation.

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/COMET-IME-Community-Edition#296]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When creating a model you are not allowed to add active domains. This can be done though a subsequent Edit of the model. Now, when creating the Active Domain tab is there and correctly you cannot select any domains. But from the usability point of view it looks as if it is not working. To make more clear to the user that they cant select any domains, the checkboxes should be either grayed out or the entire tab made invisible in create mode.

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
related to #73

**Comment by lxatrhea** [comment]
Fixed in #766
