### ISSUE TITLE
Deprecated ParameterTypes erroneously visible

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/COMET-IME-Community-Edition#442]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The ParameterType list at the bottom of the ParameterizedCategoryRulesDialog contains deprecated ParameterTypes even when the Show Deprecated state is off.
It should visually follow the general Deprecated Item rules.

Should be able to implement the FilterStringService.

- [ ] Do R&D on hooking up to the FilterStringService
- [ ] Implement solution
- [ ] Find other places where this could be a problem and implement the same solution there

**Comment by samatrhea** [comment]
no, this is not correct behaviour

**Comment by alexatrhea** [comment]
Might be fixed already, need to verify.

**Comment by MartinFijneman** [comment]
verified with 9.2.0-RC1
