### ISSUE TITLE
Close guard unsaved changes

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/COMET-IME-Community-Edition#627]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
There are several ways to close a report that has changes in DataSource, or Report Designer, without any warning.
Close guards need to be implemented for these situations:

- Close the application
- Close the report panel
- Create a new report
- Open another existing report

In all these cases a messagebox with a confirmation question should be shown, stating that the report has unsaved changes.
Ask what the user wants to do and implement Yes / No buttons.

There is a partial implementation in ReportDesignerViewModel.IsSwitchReportProjectAllowed
Getting the value of the ReportDesignerDocument.HasChangesProperty doesn't seem to work. (since some DevExpress update, this works again)

**Comment by lxatrhea** [comment]
Solution makes use of BrowserViewModelBase.IsDirty property, which makes it suitable for all browsers that have an IsDirty implementation.

**Comment by MartinFijneman** [comment]
verified with 901 RC2 for all cases:

-     Close the application
-     Close the report panel
-     Create a new report
-     Open another existing report
