### ISSUE TITLE
Create compound parameter type - short name field for components looses focus after each character when typing

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/COMET-IME-Community-Edition#669]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

create compound parameter type - short name field for components looses focus after each character when typing, so user has to activate field after each character.

field should not loose focus when typing

![image](https://user-images.githubusercontent.com/35371313/104040896-83be3a80-51d8-11eb-91ae-40e971d1471b.png)

### Steps to Reproduce

open parameter types browser
select menu item to create new compound parameter
add component to compound
try to type short name in field

### Logs

  - [x] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 7.0.0.6
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by alexatrhea** [comment]
@omaratrhea good first issue for you
