### ISSUE TITLE
Expand All - Element Definition Tree and Product Tree

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-IME-Community-Edition#735]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Add an "expand all" context menu item to the Element Definition tree and product tree. See requirements tree for inspiration and existing functionality

### Steps to Reproduce
NA

### Logs

  - [x] There are no logs regarding the issue

  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 7.0.0.6

**Comment by samatrhea** [comment]
![image](https://user-images.githubusercontent.com/22165725/127459357-415f5bce-2614-45d0-889f-1aa6d038d3fa.png)

**Comment by SimonWoodRhea** [comment]
The expand rows functionality already appears to be present in both Element Definition tree and Product Tree and works as indicated

**Comment by samatrhea** [comment]
ok, then we can close this isse
