### ISSUE TITLE
Switch Domain dialog should show Currently Selected Domain instead of Default Domain

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/COMET-IME-Community-Edition#761]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Currently the domain dropdown in the ModelIterationSwitchDomain view always shows the Person's default domain.
This should be the currently active Domain.

Change should be made in ModelSelectionIterationSetupRowViewModel class.
Currently Selected Domain should become available to the ModelSelectionIterationSetupRowViewModel.

**Comment by MartinFijneman** [comment]
verified with 9.2.0-RC1
