### ISSUE TITLE
CDP4-IME RAM optimization

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-IME-Community-Edition#765]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
An issue where we can make record of the ideas or possible issues where we can potentially improve:
  - CDP4EngineeringModel.ViewModels.ParameterOrOverrideBaseRowViewModel: I think we need to refactor the SetProperties method that seems to be creating many duplicate listeners (IDisposables)
  - CDP4EngineeringModel.ViewModels.ParameterBaseRowViewModel: i think the Dispose method is not properly implemented.

**Comment by lxatrhea** [comment]
Looks like CDPMessageBus listeners are the biggest RAM users.
Partially disabling them in ElementDefinitionBrowser's child RowViewModels (ElementDefinitionRowViewModel, ElementUsageRowViewModel and their nested children).
Several solutions could make a big difference in performance and memory usage:

- Upgrading RX libraries
- Checking our CDPMessageBus implementation
- Upgrading ReactiveUI
- Implementing CDPMessageBus without using RX libraries.
