### ISSUE TITLE
New model creation active domain of expertise cannot be selected

### ISSUE THREAD

**Issue by adrianchivu** [RHEAGROUP/COMET-IME-Community-Edition#766]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Active domain cannot be selected in the new model creation window.

**Comment by adrianchivu** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/47980674/110302564-0c532e80-8002-11eb-813e-a8b6d7976ee9.png)

**Comment by samatrhea** [comment]
as per 10-25, it is not allowed to edit the active domains as part of a create on EngineeringModelSetuo (even though this is not very explicit). Do you need this to be more explicit in the GUI by disabling this tab?

**Comment by adrianchivu** [comment]
Thanks for the response. I will share your proposal with ESA(Johan Vennekens).

**Comment by JVennekens** [comment]
I agree with the proposed solution. It would be better if the Active Domain tab would be disabled similarly how the Organizations tab is greyed out, or simply not visible in the create model GUI.
