### ISSUE TITLE
Improve Annex c3 export user experience

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/COMET-IME-Community-Edition#779]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
1. Improve the export button in the ribbon. Right now there are 2 buttons, as it needs to change to one with a clear label.
2. Improve the look and feel of the Annex c3 file export dialog. Right now it feels cramped and somewhat convoluted.
3. Ensure Password field verification works. (Also check #211)

**Comment by samatrhea** [comment]
this is related to https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues/211 and needs to be taken into account when refactoring the dialog\
