### ISSUE TITLE
Export RelationshipMatrix to Excel

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/COMET-IME-Community-Edition#785]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Related to #752 and #786

As a user I would like to export the relationship matrix to/from a .csv and .xlsx file.

When opening them in excel, I would like to see tree sheets:

- One which simply shows the matrix as it is on CDP4
- A second sheet with the list of relationships shown in the matrix and their attributes in columns (e.g. source, forward name, target, category, owner, etc. taken from BinaryRelationship and BinaryRelationshipRule setup)
- A third sheet with the info on matrix configuration setup

**Comment by alexatrhea** [comment]
Dealt with in #1152

**Comment by MartinFijneman** [comment]
verified with 9.4.0.2 and 9.4.1.0

export is working now. Implementation slightly different from original description:

[v] One which simply shows the matrix as it is on CDP4
> shows the matrix, with some extra information on the relationship type that is used, as well as counters on row/columns

[] A second sheet with the list of relationships shown in the matrix and their attributes in columns (e.g. source, forward name, target, category, owner, etc. taken from BinaryRelationship and BinaryRelationshipRule setup)

> this is not separately included now in the export. I created this as a separate follow-up issue and close this issue

reported as #1248 

[V] matrix configuration setup given

![image](https://user-images.githubusercontent.com/35371313/235875417-51f1c72a-c5b1-4a23-9484-1ba62fd0dde6.png)
