### ISSUE TITLE
The team composition list should be collapsed by default. 

### ISSUE THREAD

**Issue by JVennekens** [RHEAGROUP/COMET-IME-Community-Edition#799]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the COMET-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The team composition list opens fully expanded, this is not easy to quickly see who the participants to the model are. The list should be displayed collapsed by default. 

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by cozminvelciu** [comment]
It would also be nice to have the collapsed entries grouped by some criteria (Domain) by default.
