### ISSUE TITLE
The option to unsubscribe to multiple parameters would be useful.

### ISSUE THREAD

**Issue by JVennekens** [RHEAGROUP/COMET-IME-Community-Edition#800]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the COMET-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I can already subscribe to multiple parameter at the same time, however it would be useful to be able to unsubscribe to multiple parameters at the same time.

Solution 1:
Select rows in the ElementDefinition browser.
If there are any Parameter Subscription rows within the selection, a context menu option "Unsubscribe selected" appears and lets you unsubscribe from all Parameter Subscriptions in the selection
I.c.w. filtering, a whole set of necessary Parameter Subscriptions can be found and selected quickly.
Show a confirmation dialog that shows the message "xxx Parameter Subscriptions will be deleted. Are you sure?"
The dialog has Yes and No buttons.

Solution 2:
Similar to the bulk subscription, have a bulk unsubscription dialog that lets you choose certain properties of the parameter subscriptions to be deleted (Owner, Category, Parameter Type etc.).
Show a confirmation dialog that shows the message "xxx Parameter Subscriptions will be deleted. Are you sure?"
The dialog has Yes and No buttons.

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by alexatrhea** [comment]
Preferably to have a design brainstorming session with @JVennekens and @samatrhea involved as there could be several useful approaches to do this.

**Comment by lxatrhea** [comment]
@JVennekens and @samatrhea, we added two possible solutions to the issue text. 
Which one do you prefer?

**Comment by JVennekens** [comment]
Both options seen useful, however if one option has to be chosen I would go for the option that allows us to bulk unsubscribe in the same manner as bulk subscribe -> option 2.
However the possibility to perform more actions with the multi select is a useful one, (multi subscribe/unsubscribe, copying, creation of usages, ...) and might be useful to be looked into in the future.

**Comment by samatrhea** [comment]
lets go for option 2 then

**Comment by MartinFijneman** [comment]
tested in 9.1.0 RC1, verified:

working as expected with different cases:
* include uncategorized
* include/ exclude specific owner domains
