### ISSUE TITLE
Cannot save BinaryRelationship on a non-COMET server

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/COMET-IME-Community-Edition#821]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
On old CDP4 (before version 6.1.0) servers, or non-COMET servers you cannot save a BinaryRelationshop using the BinaryRelationshop Dialog.
Validation states that the Name property is mandatory, but the server doesn't recognise this (COMET extension) property.

- [x] Fix mandatory nature of the RelationShip.Name property
- [ ] Fix problem that the Name property cannot be saved in non-COMET, or a server having CDP4 Model version < 1.2.

**Comment by samatrhea** [comment]
would be good to state what is 'old' here. Please let me know which server version is not working. The server version is communicated in the HTTP header of the server
