### ISSUE TITLE
Requirement Specification Editor

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-IME-Community-Edition#838]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When a requirement is not owned and hte participant does not have the permissions to edit the requirement, the specification editor allows a user to edit the text (Definition) of the requirement. 

The spec-editor needs to make use of the Permission Service to enable/disable the button used to edit a requirement and the requirement text

### Steps to Reproduce
  1. open the spec editor
  2. edit a non owned requirement and see that the text box goes to edit mode even if the requirement is not owned

### Logs
  - [x] There are no logs regarding the issue
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 8.1.0.2

**Comment by MartinFijneman** [comment]
verified with 9.2.0-RC3
tested with domain expert user; not possible anymore to edit requirement description for requirements from other domain(s)
