### ISSUE TITLE
Documentation website (cdp4docs.rheagroup.com) not available

### ISSUE THREAD

**Issue by jamiewhths** [RHEAGROUP/COMET-IME-Community-Edition#851]
Hello,

The CDP4/COMET-IME documentation usually available at http://cdp4docs.rheagroup.com/ has been inaccessible for ~2 weeks. Has it been moved?

Thanks,
Jamie

**Comment by samatrhea** [comment]
Dear @jamiewhths seems the server hosting the docs was down, it has been restarted and the docs are available again.
