### ISSUE TITLE
dotnet version clarification

### ISSUE THREAD

**Issue by nlmave** [RHEAGROUP/COMET-IME-Community-Edition#855]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The COMET IME release notes state that dotnet 4.5.2 is needed to run COMET (see https://github.com/RHEAGROUP/COMET-IME-Community-Edition/releases/tag/8.1.0).

However dotnet 4.5.2 is announced end-of-line by April 2022 (see https://dotnet.microsoft.com/platform/support/policy/dotnet-framework).

Most company compliance rules **require** to support latest dotnet releases to ensure all security fixes are included.
Relevant questions therefore are:

1. does COMET IME also work with dotnet 4.8; are there technical limitations to stick to 4.5.2 explicitly?
2. when does COMET migrate to dotnet 4.8 to ensure a future proof solution?
3. what other COMET components have the same dependency on dotnet? and what is the answer to (2) for all of them?

### Steps to Reproduce

Not applicable - see description

### Logs
  - [x] There are no logs regarding the issue
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 8.1.0 (see releases page)

**Comment by samatrhea** [comment]
Currently COMET-IME only works with .NET 4.5.2, work is ongoing to removed dependencies that will allow us to upgrade to .NET5. The COMET Webservices target .NET 4.7.2.

In the coming weeks the COMET development team will be working on the following:
  - COMET-IME remove dependency on the PRISM library, this is the major dependency binding us to .NET 4.5.2. The branch where part of this work is being performed can be found here: https://github.com/RHEAGROUP/COMET-IME-Community-Edition/tree/feat/GH833-replace-prism. This is described (even of the description is barebones) on the roadmap: https://github.com/RHEAGROUP/COMET-IME-Community-Edition/wiki/Roadmap.
  - COMET Web Services: removed dependency on NancyFx and replace with CarterCommunity to upgdare to dotnetcore (i.e. .NET5). This will also removed the dependency on Mono (for Linux installations) and will allow us to host the application using the high performance Kestrel webserver. Work is ongoing on branch https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/tree/GH104-refactor-using-carter. The code is fully functional and all integration tests from the integration test suite are passing. Last bit of work is updating the deployment strategy and doing final automated and manual verification. This is described on the roadmap: https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/wiki/Roadmap
  - The C# COMET-SDK provides support for _all_ .NET targets/frameworks, we are targetting the following monikers: targets: net45;net451;net452;net46;net461;net462;net47;net471;net472;net48;netstandard2.0;netstandard2.1;netcoreapp3.1 and leaves the choice to the users of the libraries to choose their target of choice.

if you have more questions, feel free to continue on this tread.

**Comment by nlmave** [comment]
Thanks for this answer - understood. Note that issue #856 has IMHO higher prio on short term.

**Comment by samatrhea** [comment]
@nlmave we have succeeded in removing the dependency on the PRISM library which opens the door to upgrade to the most recent version of the dotnet framework for the IME

**Comment by samatrhea** [comment]
@nlmave  we have just released version 9-RC1 which uses net48, you can find it here: https://github.com/RHEAGROUP/COMET-IME-Community-Edition/releases/tag/9.0.0-rc1

**Comment by nlmave** [comment]
Great news! Thanks for all efforts involved to resolve this. Does 9.0-rc1 also address issue #856 , which is even more important for in-company distribution? Op 6 aug. 2021 17:55 schreef Sam Gerené ***@***.***>:
@nlmave  we have just released version 9-RC1 which uses net48, you can find it here: https://github.com/RHEAGROUP/COMET-IME-Community-Edition/releases/tag/9.0.0-rc1

**Comment by samatrhea** [comment]
since the IME now requires net48 i close this issue.
