### ISSUE TITLE
COMET IME MSI installers not signed

### ISSUE THREAD

**Issue by nlmave** [RHEAGROUP/COMET-IME-Community-Edition#856]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The installers provided for the COMET IME (and possibly other tools as well) are not digitally signed. This leads to immediate warnings on Windows as installing unsigned MSI installers is by default blocked. In order to allow installation on company wide distributions, the identity and authenticity of the MSI installers must be guaranteed.

It is therefore strongly recommended that RHEA introduces a PKI solution to sign all formally delivered installers - including md5 hashes of the binaries such that downloaders can verify the authenticity of the binary and its origin.

### Steps to Reproduce

Run IME installer on any Windows 10 machine with default security settings and Windows Defender will immediately complain!

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 8.1.0 (I tried x64)
  - [x] Windows OS (32/64 bit):  64-bit Windows 10 - version 20H2

**Comment by samatrhea** [comment]
a EV Code Signing certificate has been ordered, we are going through the vetting process. As soon as the certificate is available subsequent installers will be digitally signed with Immediate reputation with Microsoft SmartScreen Filter which removes warning messages to end users that the application might be malicious

**Comment by samatrhea** [comment]
Dear @nlmave, release 9.2.0 has been signed https://github.com/RHEAGROUP/COMET-IME-Community-Edition/releases/tag/9.2.0. All releases after will be signed as well.

**Comment by nlmave** [comment]
Great! Don't forget to update the published md5/sha256 sums.

**Comment by samatrhea** [comment]
@nlmave of course
