### ISSUE TITLE
Associated File

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/COMET-IME-Community-Edition#866]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Associate a file with any Architectural Definition Diagram and save in DomainFileStore.

| Done | Requirement | Description |
| --- | --- | --- |
| <ul><li>[ ] </li></ul> | GCD-FSR-0690 | The software must provide user interface to upload a file and automatically associate it with any Architectural Definition Diagram.
| <ul><li>[ ] </li></ul> | GCD-FSR-0691 | The associated file must be stored in the DomainFileStore.

**Comment by alexatrhea** [comment]
Requirement satisfaction assured through manually uploading a file to the DFS and creating a binary relationship between it and the Diagram.
