### ISSUE TITLE
As a user i want to create a diagram with Things and relationships and persist this information for later use to the data-source

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-IME-Community-Edition#89]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Create a diagram plugin that allows a user to create, inspect, edit diagrams and their content

### Steps to Reproduce
N.A.

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 1.0.23

**Comment by naronatrhea** [comment]
I believe this feature should already exist

**Comment by samatrhea** [comment]
a number of detailed issues have been created labelled diagramming. This issue can be closed as diagramming is being implemented
