### ISSUE TITLE
Create ClassKind overload in DialogNavigationService

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/COMET-IME-Community-Edition#896]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
- [ ] Create DialogNavigationService.NavigateModel overload that takes a ClassKind as a parameter.
- [ ] Create a DialogNavigationService.IsClassKindDialogRegistered method that takes a ClassKind as a parameter and returns a boolean if it is registered using the ThingDialogViewModelExportAttribute.

**Comment by alexatrhea** [comment]
I actually don't think we need this. While investigating where would would want to use it I remembered we have `ThingDialogNavigationService` and even better `ExecuteCreateCommand` in `BrowserViewModelBase` which already does all we thought need to do.

So I'm closing it. If you remember anything extra, please reopen.
