### ISSUE TITLE
One can edit by only one letter at a time the shortNames of arrayParameterType's component

### ISSUE THREAD

**Issue by MarnixVerkammen** [RHEAGROUP/COMET-IME-Community-Edition#927]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When you create, or edit an arrayParameterType, and you want to rename the shortname of a component, Comet locks you out of the shortName box after a single keyboard click. Thus, one can only edit trhe shortname by 1 letter at a time. Also, if Backspace is pressed, Comet locks you out of the shortName box.

Note that by "lock you out", I mean that your cursor is no longer in the box. This therefore forces you to use your mouse to click once again where you want your cursor to be, before being able to make a next change.

### Steps to Reproduce
- Create a new arrayParameterType, or edit an old one.
- Try to fill in the shortName box of (one of) the component(s). You'll see that you get locked out after the first keyboard click.

You will see that the same happens if you change the dimension and therefore number of components. In each component, Comet only allows you to edit the shortname by one keyboard touch at a time.

### Logs

  - [x] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 8.1.0.2
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: don't know
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
this is fixed, duplicate
