### ISSUE TITLE
Data Source Selection window - show password button no longer working

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-IME-Community-Edition#933]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The **show** password button no longer shows the password when clicked

### Steps to Reproduce

- pop data source selection window
- click **show** button and see that nothing happens - expected is that password becomes visible and is no longer masked

![image](https://user-images.githubusercontent.com/22165725/132004661-d4e8a94c-ffef-4984-a416-69a152f7af98.png)

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 9.0.0.1

**Comment by alexatrhea** [comment]
@omaratrhea

**Comment by MartinFijneman** [comment]
verified with 9.2.0-RC1
