### ISSUE TITLE
Domain File Store - downloading file doesn't always seem to work

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/COMET-IME-Community-Edition#962]
**RELATED TO https://github.com/RHEAGROUP/COMET-SDK-Community-Edition/issues/244**

### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Domain File Store - downloading file doesn't always seem to work

In engineering model 20211007 release testing RC1 model2 created a domain file store, with folders and some testing files:
* txt file
* word file
* pdf file

Downloading a file is possible in 3 ways:
* direct download through context menu item on file
* inspect file > inspect the revision, download icon
* edit file > inspect the revision, download icon

For me somehow in several tries and attempts, I was only able to download the pdf file, and I think that was when using the 3rd option.
Separate investigation required to see if this is something that goes wrong for me, or if it is a reproducible issue (for other users) in the implementation.

Points of attention:
* domain file store created for a newly created domain "Test A" in earlier testing steps

![image](https://user-images.githubusercontent.com/35371313/136827182-274715e9-3a3f-4592-a3b4-2437fd4c9ac3.png)

### Steps to Reproduce

for model given above, try to download the given files in the domain file store 

### Logs

  - [x] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 9.1.0 RC2
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by lxatrhea** [comment]
@lxatrhea Please check if still valid.

**Comment by lxatrhea** [comment]
Seems indeed still valid.

**Comment by GMusso188** [comment]
I have tried just with .xlsx file and had the same error.
Found a workaround that is to save the file with a 1 to 4 digits name "1.xlsx", "264.xlsx" up to "9999.xlsx"

I have not tried it with other types of file but might be working as well.

**Comment by MartinFijneman** [comment]
verified with 9.3.0 RC1
tested for2 files, a txt and a docx, download working using 3 possiblities:

    direct download through context menu item on file
    inspect file > inspect the revision, download icon
    edit file > inspect the revision, download icon
