### ISSUE TITLE
Huge delay in UI response for Element Definitions tab under Model view

### ISSUE THREAD

**Issue by nlmave** [RHEAGROUP/COMET-IME-Community-Edition#978]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
There is an unacceptable delay between pressing the "Element Definitions" icon in the Model view ribbon and opening of the tab that contains the info. In our set-up this takes 3 to 10 seconds, with NO response in the UI. The problem is that the user *thinks* that he didn't press the button, as there is no visual feedback; this leads to behavior where users will press the button multiple times, leading to even longer delays in response. Note: the "busy loading" indicator only becomes visible AFTER the Element Definitions tab is shown in the UI.

It seems that the loading takes place in the UI thread and hence blocks the update of the UI itself.

### Steps to Reproduce

1. Open any large model
2. Go to Model View
3. Press "Element Definitions" icon in the ribbon
4. The Element Definitions tab appears after 3-10 seconds, depending on size of the model.

### Logs

No logs provided. Tested both on CITRIX as well as "native" configurations - almost same behavior. Problem is not related to local client setup - it is reproducible on multiple machines. Likewise the issue is not server related, we have tested it on two servers, and get same behavior. Server performance is nominal, as are data loading times reported back in the UI.
  
### System Configuration

- COMET version:
  - [x] COMET-IME: v9.0.1
- Web Services:
  - [x] CDP4/COMET Web Services version: v7.0.2
- Environment (Operating system, version and so on):
  - [x] Windows OS (32/64 bit): W10 (fully up-to-date)
  - [x] Additional information: connected to server over VPN (but seems irrelevant - other features work fine, and data is already loaded, so it is a pure IME local thing)

**Comment by MartinFijneman** [comment]
verified in testing with 9.1.0 RC2

working for implemented browser: ED, requirements browser, product tree
