### ISSUE TITLE
loading times shown in info toolbar are infinite precision

### ISSUE THREAD

**Issue by nlmave** [RHEAGROUP/COMET-IME-Community-Edition#979]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The user feedback given in the toolbar, on loading times, is shown in infinite precision, which looks weird. Cosmetic issue, and probably simple to fix. Please no more than 3 digits after the dot (msec level). Check for same problem in other views too....

### Steps to Reproduce

1. Open model
2. Go to "Model" view
3. Press "Element Definitions" icon in ribbon
4. Check the Info toolbar at the bottom of the UI: it shows "took xx:xx:xx.yyyyyyyyy" 

### Logs

  - [x] I have attached a log file or included the relevant section in this issue  

![image](https://user-images.githubusercontent.com/6161283/139586691-4f3f6312-ac6a-4b0a-ba52-5085cdd1e202.png)

### System Configuration

- COMET version:
  - [x] COMET-IME: v9.0.1
- Web Services:
  - [x] CDP4/COMET Web Services version: v7.0.2
- Environment (Operating system, version and so on):
  - [x] Windows OS (32/64 bit): W10 (latest patches)

**Comment by samatrhea** [comment]
information now shown as requested:
![image](https://user-images.githubusercontent.com/22165725/139873162-133471f0-8377-4d08-a1d0-c810964af278.png)
