### ISSUE TITLE
Dashboard plugin is not accessible from the Ribbon anymore

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/COMET-IME-Community-Edition#990]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The Dashboard button isn't present anymore in the IME Ribbon.

**Comment by MartinFijneman** [comment]
verified in testing with 9.1.0 RC2
